### ISSUE TITLE
Weird black lines appearing when I display two surfer grid surfaces?

### ISSUE THREAD

**Issue by hal98x** [3ptscience/steno3dpy#125] opened 2017-04-11 04:19 UTC
I am on Windows 7 running anaconda 2.7.12 and Jupyter Notebook. I was running Jupyter in IE but visualizing my model in Chrome. I loaded two surfer grid files as surfaces with the code below. 

import numpy as np
import steno3d
import steno3d_surfer

proj = steno3d.Project(
    title='Schmitz 44-30 ERT and EM Project',
    public=False
)

parser = steno3d.parsers.grd('Data_for_lines_stations.grd')
parser.parse(proj, as_topo=True)

proj.resources[-1].title = 'Topography'

m = proj.resources[-1].mesh

parser = steno3d.parsers.grd('Data_for_lines_stations_subsf.grd')
parser.parse(proj, as_topo=True)

proj.resources[-1].title = 'Bottom of Saturated Zone'

m = proj.resources[-1].mesh

steno3d.login()
proj.upload()

[Data_for_lines_stations_subsf.zip](https://github.com/3ptscience/steno3dpy/files/912103/Data_for_lines_stations_subsf.zip)

I see a bunch of black lines converging to a point offscreen. (See attached screen shot)

![steno_error](https://cloud.githubusercontent.com/assets/5559354/24892524/25ed7610-1e32-11e7-8db4-98df30d8b4df.jpg)

Sincerely,

Michael Wallace

**Comment by mfirmin** [comment] 2017-04-11 15:38
Hi Michael,

We're having trouble reproducing this. It seems to work fine when I try it.

Would you mind answering a few other questions, to help me track down the issue?

- Do you know what version of Chrome you're using, and which graphics card you have? 
- Does it work in other browsers? (Firefox?)
- And, is this the only project where you've noticed this?

Thanks much,
-Michael

**Comment by mfirmin** [comment] 2017-04-11 16:01
So, looking into it a bit more, it looks like the `z` values uploaded with the Grid2D's contain `NaN`s. Unfortunately, this isn't supported in steno at the moment. I'm guessing that your graphics card is treating the `NaN`s as zeroes, which is why you're seeing the lines converging off. 

If you were to replace all the `NaN`s with some other value, such as the average height of the surface, it should work properly. Then this part of the geometry should still be hidden if the associated data at these points is `NaN`.

**Comment by fwkoch** [comment] 2017-04-11 16:07
@hal98x - For example, you can add this to your code above:
```
...
m = proj.resources[-1].mesh
m.Z = np.where(np.isnan(m.Z), np.nanmean(m.Z), m.Z)
...
```
That will replace the NaN topography with the mean value. These replaced values will not show up as long as the associated dataset (which still has NaN values) is selected.

**Comment by hal98x** [comment] 2017-04-11 16:12
I tried the code again and got the same result in chrome more black lines. On IE I dont see the black lines. 

Also on IE zooming with the scroll bar doesn't work very well. It either zooms out or zooms in with just one small touch. The keyboard zoom with the + sign works well. I am going to continue using IE as the lines in chrome aren't helpful.

**Comment by fwkoch** [comment] 2017-04-12 14:56
@hal98x - I'm glad things are working ok on IE. We've created internal issues regarding the black lines and IE zooming, so I am going to close this issue.

**Closed by fwkoch** 2017-04-12 14:56 UTC
